### ISSUE TITLE
Defaults traits for link block

### ISSUE THREAD

**Issue by MisterFK** [artf/grapesjs-blocks-basic#12]
Hi,
Is it possible to update a basic-block traits?
I try to select by default the option "this window" and delete the other option.

Thanks for your help !

**Comment by artf** [comment]
You can update any aspect of the block
```js
const linkBlock = editor.BlockManager.get('link');
linkBlock.set({
	content: {
		...linkBlock.get('content'), // current content
		traits: [...],
	}
})
```
