### ISSUE TITLE
Import plugin not working in me

### ISSUE THREAD

**Issue by pipzpadilla** [artf/grapesjs-blocks-basic#13]
import React, { PureComponent, Fragment } from 'react';
import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import _ from 'lodash';
import grapesjs from 'grapesjs';
import 'grapesjs/dist/css/grapes.min.css';
import './grapes.css';

class FileName extends PureComponent {
  static propTypes = {}

  static defaultProps = {}

  componentDidMount = () => {
    grapesjs.init({
      fromElement: 1,
      container: '#gjs',
      height: '700px',
      width: 'auto',
      plugins: [
        'gjs-blocks-basic',
      ],
      pluginsOpts8: {},
    });
  }

  render() {
    return (
      <Fragment>
        <div id="gjs" />
      </Fragment>
    );
  }
}

const mapDispatchToProps = () => ({});

const mapStateToProps = () => ({});

const enhance = _.flowRight([
  withRouter,
  connect(mapStateToProps, mapDispatchToProps),
]);

export default enhance(FileName);

**Comment by artf** [comment]
You forgot to import the plugin
`import 'grapesjs-blocks-basic'`
