### ISSUE TITLE
Styles not loaded when using setComponents

### ISSUE THREAD

**Issue by keithstric** [artf/grapesjs-blocks-basic#16]
If I set the canvas html via editor.setComponents(_someHtml_) the styles are not loaded. Once I drag a block into the canvas, the styles for that particular block are loaded and everything then gets the proper style.

**Comment by artf** [comment]
Yeah, styles are blocks specific, so if, for example, you don't drop the column block you will not see its style (which makes sense). So if you need styles from beginning you have to import them first manually
