### ISSUE TITLE
Cannot remove building blocks from the blockslist

### ISSUE THREAD

**Issue by Aksh0377** [artf/grapesjs-blocks-basic#19]
pluginsOpts: {
        // 'gjs-preset-newsletter': {
        //   inlineCss: true,
        //   // ... other options
        // },
        basicBlocks: {
           blocks:['column1', 'column2', 'column3', 'column3-7', 'text', 'image', 'video'],
           },
}
Here I am trying to remove map but still map is visible.

**Comment by artf** [comment]
`basicBlocks` -> `gjs-blocks-basic`
