### ISSUE TITLE
Prefix DOM element classes to avoid CSS collisions

### ISSUE THREAD

**Issue by tomichal** [artf/grapesjs-blocks-basic#2]
This is an issue originally opened here: https://github.com/artf/grapesjs/issues/471
I created a patch with a fix ready to be pushed. How can I contribute it?

**Comment by artf** [comment]
Thanks @tomichal you can send a PR of your fix on this repo

**Comment by tomichal** [comment]
Thanks @artf, just created https://github.com/artf/grapesjs-blocks-basic/pull/3

**Comment by artf** [comment]
Merged https://github.com/artf/grapesjs-blocks-basic/pull/3 👍
