### ISSUE TITLE
Custom settings

### ISSUE THREAD

**Issue by KaytotheH** [artf/grapesjs-blocks-basic#25]
Hello, I am trying to add some additional settings to already existing blocks, but I cannot find any documentation about that. I have tried to take another approach but no use, nothing worked. any help is appreciated.

**Comment by KaytotheH** [comment]
@artf do you have any comment on the topic?

**Comment by artf** [comment]
Blocks can be easily [updated programmatically](https://grapesjs.com/docs/modules/Blocks.html#programmatic-usage)
