### ISSUE TITLE
Nearly half the packages specified have high risk vulnerabilities, all have some vulnerability.

### ISSUE THREAD

**Issue by AmtechInnovarch** [artf/grapesjs-blocks-basic#33]
After `npm i` we can see that the level of vulnerabilities is unacceptable.

```
added 646 packages from 383 contributors and audited 762 packages in 7.892s
found 724 vulnerabilities (353 low, 23 moderate, 348 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

I'm trying to fix the problem, at least locally. It will take a long time because every single specified package has a vulnerability.

**Comment by artf** [comment]
https://github.com/GrapesJS/blocks-basic/releases/tag/v1.0.2
