### ISSUE TITLE
Add initial input values for text blocks and linked text blocks to the plugin options.

### ISSUE THREAD

**Issue by devshun** [artf/grapesjs-blocks-basic#39]
@artf 

Hi, This is a great plugin.
I am using it for my project.
I really appreciate it.

I have only one complaint.

I am using this plugin in Japanese, and the labels for the blocks in the sidebar can be handled by the current plugin options, but when I drag and drop a block, the text, which is entered as the default value.
Specifically, I would like to be able to manage the "Insert your text here" in the plugin options.

Is it possible to add initial input values for text blocks and link text blocks to the plugin options?

**Comment by artf** [comment]
[Blocks can be updated](https://grapesjs.com/docs/modules/Blocks.html#programmatic-usage)
