### ISSUE TITLE
columns in v. 0.1.8 vs 0.1.7

### ISSUE THREAD

**Issue by kickbk** [artf/grapesjs-blocks-basic#9]
@artf I think you may have any issue with v. 0.1.8
I'm loading preset-webpage into my project and trying to drop a column onto the editor. loads an empty div with no class row or cell. So I started looking into it. I'm loading the 0.1.8 package and preset-webpage includes the min.js file. So I switched it with v. 0.1.7 and dropping the columns started working.
First I was confused because your demo shows the latest grapesjs version, but it's not using the latest preset-webpage actually and your demo is actually using 0.1.7, which is how I found out what was wrong.

**Comment by artf** [comment]
Should be solved with https://github.com/artf/grapesjs/releases/tag/v0.14.20
